version: "3"

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 3
      restart_policy:
        condition: any
      resources:
        reservations:
          cpus: "0.1"
          memory: 200M

volumes:
  caddy_data:
    driver: rexray/efs

networks:
  caddy:
    driver: overlay
